name: chatview
description: A Flutter package that allows you to integrate Chat View with
  highly customization options.
version: 1.2.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  ? android
  ? ios
  ? linux
  ? macos
  ? web
  ? windows

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  any_link_preview: ^3.0.0
  audio_waveforms: ^1.0.1
  emoji_picker_flutter: ^1.3.0
  flutter:
    sdk: flutter
  flutter_linkify: ^5.0.2
  grouped_list: ^5.1.2
  html: ^0.15.1
  http: ^0.13.5
  image_picker: ^0.8.6
  insta_image_viewer: ^1.0.2
  intl: ^0.18.0
  progress_indicators: ^1.0.0
  timeago: ^3.4.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
